name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_SECRET }}
          TARGET_REPO: username/repo
          TARGET_BRANCH: master
          BUILD_SCRIPT: cd docs && yarn && yarn build
          BUILD_DIR: src/.vuepress/dist
          CNAME: https://www.sz.com
