name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: sz-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_SECRET }}
          TARGET_REPO: uljp/sz-docs
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: cd docs && yarn && yarn build
          BUILD_DIR: src/.vuepress/dist
